# Generated by Django 6.1.1 on 2026-09-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong', models.CharField(max_length=50, unique=True)),
                ('gia_phong', models.DecimalField(decimal_places=0, max_digits=12)),
                ('dien_tich', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trang_thai', models.CharField(choices=[('trong', 'Phòng trống'), ('dang_thue', 'Đang thuê'), ('bao_tri', 'Đang bảo trì')], default='trong', max_length=20)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
