# Generated by Django 6.1.1 on 2026-09-28 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_nguoithue'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField(blank=True, null=True)),
                ('tien_coc', models.DecimalField(decimal_places=0, max_digits=12)),
                ('trang_thai', models.CharField(choices=[('hieu_luc', 'Đang hiệu lực'), ('het_han', 'Đã hết hạn'), ('huy', 'Đã hủy')], default='hieu_luc', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_thue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hop_dongs', to='quanly.nguoithue')),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hop_dongs', to='quanly.phong')),
            ],
        ),
    ]
