# Generated by Django 6.1.1 on 2026-09-28 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_hopdong'),
    ]

    operations = [
        migrations.CreateModel(
            name='DienNuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.DateField()),
                ('chi_so_dien_cu', models.PositiveIntegerField(default=0)),
                ('chi_so_dien_moi', models.PositiveIntegerField(default=0)),
                ('chi_so_nuoc_cu', models.PositiveIntegerField(default=0)),
                ('chi_so_nuoc_moi', models.PositiveIntegerField(default=0)),
                ('don_gia_dien', models.DecimalField(decimal_places=0, default=3500, max_digits=10)),
                ('don_gia_nuoc', models.DecimalField(decimal_places=0, default=15000, max_digits=10)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dien_nuoc', to='quanly.phong')),
            ],
        ),
    ]
