# Generated by Django 6.1.1 on 2026-09-28 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0004_diennuoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.DateField()),
                ('tien_phong', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tien_dien', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tien_nuoc', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tien_khac', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('trang_thai', models.CharField(choices=[('chua_thanh_toan', 'Chưa thanh toán'), ('da_thanh_toan', 'Đã thanh toán')], default='chua_thanh_toan', max_length=20)),
                ('ngay_thanh_toan', models.DateTimeField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thanh_toans', to='quanly.phong')),
            ],
        ),
    ]
