# Generated by Django 6.1.1 on 2026-09-28 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0005_thanhtoan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdong',
            name='nguoi_thue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hop_dong', to='quanly.nguoithue'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='phong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hop_dong', to='quanly.phong'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='phong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thanh_toan', to='quanly.phong'),
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vai_tro', models.CharField(choices=[('chu_tro', 'Chủ trọ'), ('nguoi_thue', 'Người thuê')], max_length=20)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tai_khoan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
